### ISSUE TITLE
Diccionario de datos

### ISSUE THREAD

**Issue by andresamengual** [Angerback/webforge#16]
¿Tienen diccionario de datos?, es que no entendemos algunos atributos de las tablas del modelo de datos.
En caso de no tener diccionario de datos ¿Cual es la función del atributo grade de la tabla test ?¿Cual es la función del atributo number de la tabla composition?
Saludos.

**Comment by PabloSalinasM** [comment]
ok vista tu solicitud- no tenemos diccionario de datos tus consultas se resolvera en la brevedad

**Comment by PabloSalinasM** [comment]
tests: Los alumnos podrán realizar múltiples pruebas, estas se basan en evaluaciones y son calificadas automáticamente, la calificación es almacenada en el atributo grade.

compositions: Dado que una evaluación se define como un conjunto de preguntas, la relación entre ambas entidades origina a compositions que como único atributo posee el número que representa el orden de la pregunta en el contexto de una evaluación en particular.
