### ISSUE TITLE
CRUD de cursos

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#17]
Necesitamos GET/POST/PUT/DELETE de 'courses'.

El GET se divide en:

GET courses - listar todos
GET courses/:id - listar un curso, dada su id

**Comment by PabloSalinasM** [comment]
ok leida. Lo resolveremos lo antes posible.

**Comment by pliskin12** [comment]
Hecho commit en rama angular_staging con la api solicitada. En Create enviar objeto {"course":{ parametros }}. En put lo mismo, metan los parametros que quieren actualizar.

GET /api/v2/courses
GET /api/v2/courses/:id
POST /api/v2/courses/                     (con objeto json)
PUT /api/v2/courses/:id                     (con objeto json, no acepta cambio de id)
DELETE /api/v2/courses/:id

**Comment by ChrisVilches** [comment]
Listo, lo probe y funciona `perfecto` ;)

**Comment by ChrisVilches** [comment]
Lo reabro porque parece que falto algo. En la version anterior obteniamos la cantidad de usuarios de cada curso haciendo @course.users.size desde la vista.

Aca que alternativa habria? Porque necesitamos obtener la lista de cursos, cada uno con su cantidad de usuarios. La idea seria hacer un join para que el JSON resultante tenga ese atributo.

Logre modificando el jsonbuilder de api/v2 colocando

json.extract! @course, :id, :name, :semester, :created_at, :updated_at, :year, **:users**

Pero eso entrega los JSONs de todos los usuarios. Habra otra forma de colocar solo el numero?

**Comment by pliskin12** [comment]
Me parece que esto entra en la otra petición que abriste, la cual estoy trabajando. Si usas /courses/id/users deberian aparecer los usuarios no? ahi podrias sacar el numero de usuarios. De hecho eso ya lo tengo, pero tengo un problema de que al agregar un usuario se pueden agregar usuarios indefinidamente a un curso, necesito validar eso. Si pueden vivir con eso (correr el riesgo de tener usuarios repetidos si los vuelven a agregar a un curso) mientras tanto te hago push para que puedas usarlo nomas

**Comment by pliskin12** [comment]
La sintaxis de la URL es tal como pediste en la otra petición

**Comment by ChrisVilches** [comment]
Mira seba, este es el archivo `courses/index.json.jsonbuilder`, agregue la linea `json.users course.users.size`, lo cual me entrega exactamente lo que quiero.

``` ruby
json.array!(@courses) do |course|
  json.extract! course, :id, :name, :semester, :created_at, :updated_at, :year
  json.url course_url(course, format: :json)
  json.users course.users.size
end
```

Resultado de hacer GET de courses

``` json
[
    {
        "id": 1,
        "name": "Curso nuevo",
        "semester": 1,
        "created_at": "2016-05-21T23:06:48.393Z",
        "updated_at": "2016-05-21T23:06:48.393Z",
        "year": 2014,
        "url": "http://localhost:3000/courses/1.json",
        "users": 2
    },
    {
        "id": 3,
        "name": "OTRO CURSO",
        "semester": 4,
        "created_at": "2016-05-21T23:09:19.248Z",
        "updated_at": "2016-05-21T23:09:19.248Z",
        "year": 2015,
        "url": "http://localhost:3000/courses/3.json",
        "users": 0
    }
]
```

**Comment by ChrisVilches** [comment]
Lo que pasa es que quiero obtener el numero de usuarios altiro, y luego obtener los usuarios de forma detallada al hacer courses/id/users, por eso queria de esa forma

**Comment by ChrisVilches** [comment]
@Angerback pudiste hacer lo de agregar la linea `json.users course.users.size` en el archivo que dije? para hacer que el JSON de un curso incluya cuantos usuarios tiene (solo el numero). Solo faltaria eso para poder cerrar este issue.

**Comment by pliskin12** [comment]
Lo agregué al index y al show, y aparece como tu lo pedías, haré el commit ahora :)

**Comment by ChrisVilches** [comment]
Aunque en el show, ahi si vamos a hacer eso de obtener los Jsons de todos los alumnos, asi que ahi no seria necesario colocar el numero de alumnos, seria una consulta desperdiciada para ese caso de uso. Pero igual no influye mucho

**Comment by ChrisVilches** [comment]
Ok estan todas probadas, funciona bien todo

GET /api/v2/courses (incluyendo atributo de cuenta de alumnos inscritos)
GET /api/v2/courses/:id
POST /api/v2/courses/ (con objeto json)
PUT /api/v2/courses/:id (con objeto json, no acepta cambio de id)
DELETE /api/v2/courses/:id
