### ISSUE TITLE
CRUD de usuarios

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#18]
Se requiere CRUD de usuarios (get/post/put/delete). Y al igual que en cursos, el GET se divide en listar todos, y en listar uno solo, dada su ID (ejemplo: /users/4).

Edit: Si pueden, utilicen el mismo metodo de paginacion que ya tienen (el que permite URLs como /users?page=2)

**Comment by PabloSalinasM** [comment]
ok leida. Lo resolveremos lo antes posible. Recuerda si marcan todas con urgente se le dara la misma prioridad a todas esas. Saludos

**Comment by yeremix** [comment]
El get de usuarios ya esta implementado tanto para todos como para 1 usuario.
El post de usuarios ya esta implementado desde esta mañana.
El put se espera tenerlo listo lo antes posible, trabajaremos en ello.
El delete, creo que se había acordado que no eliminaríamos usuarios sino solo los deshabilitariamos :3

**Comment by pliskin12** [comment]
Están hechos todos menos delete y put. Estamos trabajando en ellos.

Lo que hay:

GET /api/v2/users
GET /api/v2/users/:id
POST /api/v2/users/ (con objeto json{"user": {parametros}})

para paginar concatenar ?page=NUMEROPAGINA a la url ;)

Está en la rama angular_staging

**Comment by pliskin12** [comment]
Hecho PUT y DELETE

PUT /api/v2/users/:id (con objeto json, no acepta cambio de id)
DELETE /api/v2/users/:id

**Comment by ChrisVilches** [comment]
@Angerback Falta una cosa en el GET de `users/:id`

**Edit:** no es necesario hacer esto, no lo lean. Me di cuenta que se puede hacer con el CRUD de calificaciones. Pero no borrare el mensaje por ahora en caso que me de cuenta que hay un problema.

Si te fijas en el controlador `users_controller.rb`, pasa como variables globales (con `@`) mas datos, los cuales se obtienen a traves de las relaciones. El codigo es:

``` ruby
    def show
        @user = User.find(params[:id])
        @evaluation = Evaluation.find(1)
        @lastTest = Test.where( :user_id => @user.id, :grade =>  0.9..7.1 ).last
            @userTests = Test.where( :user_id => @user.id )
        @mejorNota = 0
        @peorNota = 7.0
        @promedioNota = 0
        sumadorNotas = 0
        cantidadNotas = 0
        @userTests.each do |test|
            if test.grade
                if test.grade > @mejorNota
                    @mejorNota = test.grade
                end
                if test.grade < @peorNota
                    @peorNota = test.grade
                end
                sumadorNotas = sumadorNotas + test.grade
                cantidadNotas = cantidadNotas + 1
            end
        end
        if cantidadNotas != 0
            @promedioNota = sumadorNotas / cantidadNotas
        end
        respond_to do |format|
            format.html { render :layout => false }
        end
    end
```

La cosa es que necesito las notas tal como las tira esta funcion, es decir, junto al JSON de usuario, colocar los otros datos como el promedio, etc. Asi es mas simple que haciendo consultas aparte, ademas que ya empece a trabajar con un "JSON falso" para implementarlo luego. (solo las notas, y no el `@evaluation`, el cual ya pude obtener con una consulta aparte)

(ese codigo esta en el controlador NO de la api.. entonces habria que pasarlo al de la api, y modificar el jsonbuilder para incluir los nuevos datos, tal como se modifico el de cursos)

**Comment by FeloVilches** [comment]
O podria ser solo las notas, y el ```@evaluation = Evaluation.find(1)``` lo sacamos desde el CRUD de evaluaciones.

**Comment by ChrisVilches** [comment]
Ya se soluciono el problema anterior (el de las calificaciones), junto con otro bug que habia. Esta todo perfecto :+1:
