### ISSUE TITLE
CRUD de la relacion usuarios-cursos

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#19]
Necesitamos URLs que permitan:

Obtener todos los alumnos que estan en un curso (ejemplo: GET courses/17/users)
Agregar alumno a un curso (ejemplo: POST courses/17/users/8)
Eliminar alumno de un curso (ejemplo: DELETE courses/17/users/8)

(PUT no es necesario)

**Comment by PabloSalinasM** [comment]
Leida.

**Comment by pliskin12** [comment]
Listo:
Obtener todos los alumnos que estan en un curso (ejemplo: GET courses/17/users)
Agregar alumno a un curso (ejemplo: POST courses/17/users/8)

Falta quitar un alumno

**Comment by ChrisVilches** [comment]
Para las HU que tenemos basta con estas operaciones
