### ISSUE TITLE
CRUD evaluations

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#20]
Se requiere CRUD de evaluaciones

**Comment by PabloSalinasM** [comment]
ok veremos las otras peticiones antes.

**Comment by PabloSalinasM** [comment]
Felipe necesitamos que se clarifique más esta petición. Queremos saber qué es  lo que quieren con las evaluaciones en sí, porque nosotros no vemos la funcionalidad de un crud en las  evaluaciones. Si nos envían alguna foto o maqueta con lo que buscas para que sea más fácil el entendimiento de esta.

**Comment by ChrisVilches** [comment]
@PabloSalinasM tienes razon. Agregaremos mas informacion/detalles cuando nosotros tambien lo tengamos mas claro.

**Comment by yeremix** [comment]
Get todos y get solo 1 elemento, Indicaciones:
Link del commit: https://github.com/Angerback/webforge/commit/b6b4d0583d10d136f69d7e020287e9c4f35605dd

Forma de acceso para los datos:
GET `/api/v2/evaluations`
GET(solo 1 elemento) `/api/v2/evaluations/:id`

donde :id es el id de la evaluación, es lo que con respecto a la petición se pudo implementar, saludos!

**Comment by ChrisVilches** [comment]
Con esto nos basta para nuestra HU, gracias.
