### ISSUE TITLE
CRUD messages y chats

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#21]
CRUD de messages y chats

Listar chats `GET /chats`
Mostrar chat `GET /chats/:id` (debe mostrar el listado de mensajes)

Con eso ya se tiene una lista de chats en donde al mostrar cada uno, se muestra la lista de mensajes. Ahora necesitamos agregar mensaje.

Agregar mensaje a un chat `POST /chats/:id` (con JSON) - URL propuesta, pero pueden cambiarla si lo estiman conveniente.

(DELETE y PUT no lo consideren, ni para messages ni para chats)

**Comment by PabloSalinasM** [comment]
ok una vez terminen con las otras se te solicitara tal vez mayor información

**Comment by fbnr** [comment]
Para esta issue es necesario el editar y el delete? (no lo veo como necesario)

**Comment by ChrisVilches** [comment]
@fbnr tampoco creo que sea necesario, solo es necesario agregar mensajes y poder obtenerlos

**Comment by ChrisVilches** [comment]
@fbnr Aca les dejo informacion sobre como debe ser el JSON de `GET chats/` (listar todos)

Aca hay un ejemplo que contiene dos chats. Son los mismos atributos que retorna en la aplicacion original. 
- **id**: id del chat
- **title**: titulo del chat
- **user**: Autor del chat (necesito solo el nombre, aunque pueden colocar el JSON completo, o como quieran)
- **ultimoMensaje**: Ultimo mensaje agregado al chat
- **autorUltimoMensaje**: La persona que hizo el ultimo mensaje

(puede tener mas atributos, pero yo solo necesito nombre)

``` json
[{
    "title": "Titulo chat",
    "id": 4,
    "user": {
        "name": "Felipe Vilches"
    },
    "ultimoMensaje": "Este es el ultimo mensaje que se ha agregado al chat",
    "autorUltimoMensaje": "Sebastian Meneses"
},
{
    "title": "Titulo chat",
    "id": 5,
    "user": {
        "name": "Veronica Dominguez"
    },
    "ultimoMensaje": "Este es el ultimo mensaje que se ha agregado al chat",
    "autorUltimoMensaje": "Francisco Vergara"
}]
```

Notese que esto es simple de implementar porque el controlador original de la aplicacion (no el de la API) ya hace todo esto, asi que solo tienen que copiar codigo.

Obtiene el `@owner` (autor del chat), `@messages` (ultimo mensaje de cada chat), `@authors` es el autor del ultimo mensaje, en cada chat.

Si tienen problemas para pasar variables con `@` al jsonbuilder vean el sintaxis usado aqui https://github.com/Angerback/webforge/blob/angular_staging/app/views/api/v2/courses/show.json.jbuilder

``` ruby
    # /app/controllers/chats_controller.rb
    def index

        # NOTA: ACA borre algunas lineas, para que sea posible ver los chats sin hacer login
        @chats = Chat.all

        @messages = Hash.new
        @authors = Hash.new
        @owners = Hash.new
        @chats.each do |chat|
            @owners[chat.id] = User.find(chat.user_id)
            @messages[chat.id] = Message.where(chat_id: chat.id).last
            @authors[chat.id] = User.find(@messages[chat.id].user_id).name
        end
```

**Comment by ChrisVilches** [comment]
Aca hay un ejemplo de show de chat. Al igual que el anterior, el codigo de Ruby es el mismo que el del controlador original, solo tienen que pasarlo a JSON. 
- **id**: id
- **title**: titulo del chat
- **user**: creador del chat (puede tener el json completo, pero solo necesito el nombre)
- **messages**: arreglo de mensajes, en donde cada mensaje tiene:
  - **id**: id del mensaje
  - **autor**: string con el nombre del autor del mensaje
  - **created_at**: fecha del mensaje. El formato puede cambiar (da lo mismo, ahi lo adapto yo)
  - **body**: contenido del mensaje

``` json
{
    "id": 2,
    "title": "Titulo del chat",
    "user": {
        "name": "Felipe Vilches"
    },
    "messages": [

        {
            "id": 2,
            "autor": "Maria Francisca",
            "created_at": "2016-05-23T21:57:12.879Z",
            "body": "Este es el contenido del mensaje"
        },
        {
            "id": 3,
            "autor": "Alan Guzman",
            "created_at": "2016-05-23T21:57:12.879Z",
            "body": "Este es el contenido del mensaje"
        },
        {
            "id": 4,
            "autor": "Conan Blasi",
            "created_at": "2016-05-23T21:57:12.879Z",
            "body": "Este es el contenido del mensaje"
        }

    ]
}
```

**Comment by ChrisVilches** [comment]
Agregar mensaje, debiera (en lo posible) retornar el JSON del mismo mensaje agregado (si no se puede no importa).

**Comment by fbnr** [comment]
Esta lista la petición, cualquier cosa avisen:

GET /api/v2/chats
GET  /api/v2/chats/:id
POST /api/v2/chats/:id/messages

Aquí te dejo el link del commit, en la rama angular_staging
https://github.com/Angerback/webforge/commit/b3b569c568d28109cab78d75cd0afd6382627d89

**Comment by fbnr** [comment]
Ejemplo de POST:

{
"body": "Este es el contenido del mensaje"
}

**Comment by ChrisVilches** [comment]
No cumple con lo que se pide.

En el controlador de chats (de la api) se ve esta linea de codigo

``` ruby
@owners[chat.id] = User.find(chat.user_id)
```

Y en el JSON no se ve por ningun lado que use `@owners`, de hecho arroja como "autor del chat" al autor del ultimo mensaje, lo cual es incorrecto ya que va cambiando dependiendo de quien es el ultimo que responde. (Esto es en index)

``` ruby
json.array!(@chats) do |chat|
  json.extract! chat, :id, :title, :user_id
  json.last_message @messages[chat.id].body
  json.author_last_message @messages[chat.id].user.name
  json.user @authors[chat.id], :name
end
```

Tampoco es correcto que el POST se haga solo con el mensaje en el JSON, tambien se debe especificar que usuario esta enviando el mensaje. 

``` json
{
"body": "Este es el contenido del mensaje"
}
```

El show tambien tiene algo incorrecto, y es que no muestra el nombre del autor, pero supongo que esto se deduce por el autor del primer mensaje, asi que ahi no hay problema.

**Comment by ChrisVilches** [comment]
Para corregirlo pueden usar este codigo para el JSON del chats INDEX:

``` ruby
json.array!(@chats) do |chat|
  json.extract! chat, :id, :title, :user_id
  json.last_message @messages[chat.id].body
  json.author_last_message @messages[chat.id].user.name
  json.autor_chat @owners[chat.id].name
end
```

El controlador del chat index esta bien como lo tienen.

**Comment by ChrisVilches** [comment]
Para modificar el POST de escribir mensaje, hay que corregir un error que hay en el controlador de messages. La linea `@owner = User.find...` lo que hace es obtener el usuario que creo el chat. Lo que hay que hacer es obtener la ID del usuario pasado por JSON.

Este es el codigo original:

``` ruby
class Api::V2::MessagesController < API::V2::ApiController

  def create
    @chat = Chat.find(params[:id])
    @owner = User.find(@chat.user_id)

    @message = Message.new(chat_id: params[:id], user_id: @owner.id, body: params[:body])
    if @message.save
      render json: @message
        #redirect_to({controller: "chats", action: "show", id: params[:id]})
    else
      head :unprocessable_entity
        #flash[:danger] = "Problemas con las publicación del mensaje"
    end
  end
end
```

La linea `@message = Message.new(chat_id: params[:id], user_id: @owner.id, body: params[:body])` hay que cambiarla para que reciba la ID del usuario que esta creando el mensaje (recibida por JSON), especificamente cambiar el `...user_id: @owner.id...`

(La ID del chat ya la esta pasando por la URL `/chats/ID_CHAT/messages`)

**Comment by ghost** [comment]
ff0524c se muestra el nombre del autor del chat en lugar de la id

**Comment by ghost** [comment]
d2b99ba POST

**Comment by ChrisVilches** [comment]
Ahora si funciona todo bien
