### ISSUE TITLE
Ver las calificaciones de un alumno

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#22]
Dada la ID de un alumno, se requiere poder ver sus calificaciones.

**Comment by PabloSalinasM** [comment]
ok leido

**Comment by yeremix** [comment]
Issue lista!, Indicaciones:
Link del commit: https://github.com/Angerback/webforge/commit/bafc2f56b9e1fc7522c005fb92a416dfc08710d5

Forma de acceso para los datos y forma requerida:
`/api/v2/users/:id/grades`

donde `:id` es el id del usuario para consultar sus calificaciones.

**Comment by ChrisVilches** [comment]
Con esa funcionalidad basta, muchas gracias :)
