### ISSUE TITLE
Deploy de la API

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#23]
Hola, para que nuestro grupo (front end) pueda trabajar en el proyecto, necesitaremos que hagan deploy de la API a heroku.

Ayer hice un deploy a heroku de mi proyecto (el de Node) y funciona hacer peticiones a webforge.herokuapp.com, y tambien funciona haciendolas desde mi localhost, por eso seria muy conveniente que la API este arriba para que nosotros no tengamos que estar descargando la rama y dejandola corriendo en nuestros PC.

Para eso tendrian que limpiar el proyecto Rails, sacar las vistas HTML, javascripts, etc, y lo mas importante, eliminar los tests que testean frontend (como ya no hay frontend, se deben eliminar), para que asi pueda correr en semaphoreci y deployear.

Es viable o habria algun problema en dejar la API corriendo?

**Comment by pliskin12** [comment]
Es viable. Sin embargo, no podemos limpiar todo, estamos implementando funcionalidades y eso toma tiempo. Lo dejaremos arriba, pero seguirán apareciendo las páginas antiguas hasta nuevo aviso.

**Comment by pliskin12** [comment]
Cuando prueben localmente las funcionalidades que les entreguemos y cierren las peticiones, haremos merge de estas a la rama staging para que así quede en heroku 24/7

**Comment by ChrisVilches** [comment]
Ah ya okay, entonces primero probare localmente si funcionan, y luego aviso para que las suban, no hay problema :)

**Comment by ChrisVilches** [comment]
Estan todas las funcionalidades listas. Yo creo que podrian hacer deploy del proyecto en Rails (API) para que el proyecto en Express se pueda comunicar con ella en Heroku ambos.
