### ISSUE TITLE
Error al hacer GET users/:id

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#25]
Al entrar en esta URL `http://localhost:3000/api/v2/users/2` me arroja el resultado correcto, pero al entrar a `http://localhost:3000/api/v2/users/1`, me arroja este error

```
NoMethodError in Api::V2::UsersController#show
undefined method `grade' for nil:NilClass

  def _extract_method_values(object, *attributes)
    attributes.each{ |key| _set_value key, object.public_send(key) }
  end
```

**Comment by ChrisVilches** [comment]
El error esta en esta linea en el archivo show.json.jbuilder de users

``` ruby
json.extract!  @lastTest, :grade
```

Debe eliminarse el `:grade`

Edit: solo la primera linea sirve, las dos restantes no, asi que se pueden borrar las dos

**Comment by ghost** [comment]
removido de show.json.jbuilder

json.set! :name_test, @evaluation.name
json.extract!  @lastTest, :grade

ahora funciona

**Comment by ChrisVilches** [comment]
Si, funciona como esperado :+1:
