### ISSUE TITLE
Solicitud API

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#30]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para crear la práctica del estudiante en la tabla excersise usando el id_usuario, id_practica[1 ,2,3 o 4], plunk[la dirección que ingrese el estudiante]). Esto es para que pueda ingresar su plunkr de las 4 prácticas presentes en la aplicación.
- necesito un método para actualizar la dirección plunkr de la práctica del estudiante en la tabla excersise(un update al atributo plunkr)
- necesito método para realizar CRUD en bank_accounts y records (lo que pertenece a la terminal bancaria)
- necesito un método para obtener la lista de prácticas(practice) del estudiante con sus atributos, pensaba que podía ser un array tipo json:
  {
  { atr1: valor,
    atr2: valor
  },
  { atr1: valor,
    atr2: valor
  }
  } (esto lo escribí a la rápidam no es que les pida este formato)

Les dejo un link donde están todas las peticiones que como G1 hemos identificado, 
rojo prioritarias
amarillo normales
verde menos importantes

https://docs.google.com/spreadsheets/d/12wt2dGkmS5gQiJnKTp2pcC_1g-wWmcv8tt3EUDm_qBc/edit?usp=sharing

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
Leido. Separar peteciones por favor. Saludos

**Comment by pliskin12** [comment]
Un estudiante no tiene practicas, tiene exercises. ¿Quizas sea eso lo que quieres?

**Comment by pliskin12** [comment]
¿Una lista con el ultimo exercise para cada practice? seria una lista de cuatro objetos si entiendo bien

**Comment by nelsonjerezv** [comment]
los 4 (objetos) excersise del estudiante, si eso gracias. y cada objeto conteniendo todos los atributos. Me pidieron descomponer estas peticiones, traté de ser un poco más claro en esas (las 4 nuevas que dicen urgente), por si te sirve :)

**Comment by pliskin12** [comment]
Ok, me referiré a las otras de ahora en adelante
