### ISSUE TITLE
Solicitud API

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#31]
Holaa, les quiero solicitar lo siguiente:   

son métodos para obtener las tablas(como un array pensaba) de  
- tests con sus atributos  
- evaluation con atributos  
- topics con atributos  
- questions con atributos  
- alternative con atributos 
- composition con atributos 

la idea es disponer de la info como se ve en estos json:
https://github.com/FeloVilches/Webforge-Express/tree/grupo1_nelson/public/jsonDataAux (ej questions y alternative)  

Junto con eso:  
- necesito un método para crear una nueva evaluación del estudiante(crear la evaluación cuando se presione "comenzar evaluación")
- necesito un método para guardar la respuesta de la pregunta actual en la evaluación actual(se guarda cada vez que presiona siguiente pregunta)

Les dejo un link donde están todas las peticiones que como G1 hemos identificado, 
rojo prioritarias
amarillo normales
verde menos importantes

https://docs.google.com/spreadsheets/d/12wt2dGkmS5gQiJnKTp2pcC_1g-wWmcv8tt3EUDm_qBc/edit?usp=sharing

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
Leido. Es necesario que hagan una petición por cada necesidad de su grupo no agruparlas todas en una para asi ser más rápida la soluciones de estas. Luego serán resueltas tus necesidades saludos.
