### ISSUE TITLE
Solicitud API - Create/Read tabla excersise

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#32]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para crear la práctica del estudiante en la tabla excersise usando el id_usuario, id_practica[1 ,2,3 o 4], plunk[la dirección que ingrese el estudiante]). Esto es para que pueda ingresar su plunkr de las 4 prácticas presentes en la aplicación.

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Api lista. En la url: http://servidor/api/v2/exercises hacer petición POST con un json del estilo:
{"user_id":2, "practice_id":4, "plunk":"http://urlfalsa", "embed":"http://fake"}

La respuesta correcta es un json:

{"outcome": "Trabajo registrado exitosamente."}
