### ISSUE TITLE
Solicitud API - Update tabla excersise

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#33]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para actualizar la dirección plunkr de la práctica del estudiante en la tabla excersise(un update al atributo plunkr)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Api lista. En la url: http://servidor/api/v2/exercises hacer petición PUT con un json del estilo:
{"user_id":2, "practice_id":4, "plunk":"http://urlfalsa2", "embed":"http://fake2"}

La respuesta correcta es un json:
{
"outcome": "Enlace a tu trabajo actualizado, Vista embebida actualizada, "
}

Por defecto edita el ultimo ejercicio para la practica y el usuario especificado en el json. Sin embargo, si quieres editar alguno anterior para ese usuario y esa practica, puedes agregar el id del exercise en la url:
 http://servidor/api/v2/exercises/2
