### ISSUE TITLE
Solicitud API - CRUD en tablas Bank_accounts/records

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#34]
Holaa, les quiero solicitar lo siguiente:
- necesito método para realizar CRUD en bank_accounts y records (lo que pertenece a la terminal bancaria)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Estás seguro que necesitas el borrar en esas operaciones? Lo otro, un record se crea cuando actualizas un bank_account, esto ya está implementado en la terminal bancaria y api original ya que ya funcionaba con angular.

Te resumo, lo que ya hay es:

Ver una cuenta bancaria para un usuario: GET /api/v1/bank_accounts/:user_id
Editar una cuenta bancaria para un usuario: PUT /api/v1/bank_accounts/:user_id (Lo que automaticamente crea un nuevo record. La idea es que los records solo se crean cuando actualizas tu saldo) Al editar se fija en un json con estos parametros: owner_id, receiver_id, operation, amount
Crear una cuenta bancaria para un usuario: POST /api/v1/bank_accounts . Al crear se usa un objeto json con los parametros balance, status, user_id.

Las respuestas en este caso son solo códigos de respuesta http, es lo que dejó hecho javier. Si sale bien te tira un OK, si sale mal te tira un unprocessable entity

**Comment by nelsonjerezv** [comment]
Toda la razón borrar no es necesario, entonces CRU está listo ya, por lo que no necesitaría nada  nuevo y se podría cerrar esta petición :)
