### ISSUE TITLE
Solicitud API - Read tabla practice

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#35]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para obtener la lista de prácticas(practice) del estudiante con sus atributos, pensaba que podía ser un array tipo json:
  [
  { atr1: valor,
  atr2: valor
  },
  { atr1: valor,
  atr2: valor
  }
  ](esto lo escribí a la rápidam no es que les pida este formato)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by nelsonjerezv** [comment]
disculpa, podrías darme un ejemplo de como sería la petición por favor?

**Comment by pliskin12** [comment]
Hola, disculpa, me equivoqué al cerrar esta, te lo subo ahora

**Comment by pliskin12** [comment]
Si lo que quieres es obtener los resultados de la ultima practica del estudiante, usa esto: GET /api/v2/users/idUsuario/exercises

**Comment by pliskin12** [comment]
O lo que necesitas es directamente los cuatro practices que hay en la BD? no para el usuario?

**Comment by pliskin12** [comment]
Por ejemplo esto es lo que te estoy mandando ahora: 

[{"id":3,"user_id":2,"practice_id":1,"plunk":"asdfasdf123123","embed":"xc1q23","created_at":"2016-06-17T20:53:26.980Z","updated_at":"2016-06-17T21:05:55.051Z"},{"id":7,"user_id":2,"practice_id":2,"plunk":"http://urlfalsa","embed":"http://fake","created_at":"2016-06-17T21:40:18.508Z","updated_at":"2016-06-17T21:40:18.508Z"},{"id":8,"user_id":2,"practice_id":3,"plunk":"http://urlfalsa","embed":"http://fake","created_at":"2016-06-17T21:40:22.299Z","updated_at":"2016-06-17T21:40:22.299Z"},{"id":10,"user_id":2,"practice_id":4,"plunk":"http://urlfalsa","embed":"http://fake2","created_at":"2016-06-17T21:45:20.289Z","updated_at":"2016-06-17T21:45:38.193Z"}]

**Comment by nelsonjerezv** [comment]
es exactamente lo que quería :)

unas dudas:

1) si ese usuario no tiene practicas, devuelve un JSON vacío?
2) si tiene creada un subconjunto, devuelve el subconjunto? (ej [{ ..., "practice_id":1, ...}, {..., "practice_id":3, ...}])

**Comment by pliskin12** [comment]
Exactamente, te devuelve un json vacío.
No entiendo lo de subconjunto. Te refieres a si tiene varios exercises para cada practice? Si es asi siempre retorna el más reciente, o sea uno por practice, nunca el subconjunto

**Comment by nelsonjerezv** [comment]
me refiero a que si de las 4 prácticas, en vez de haber iniciado todas o ninguna (JSON con los 4 o con ninguno), ha iniciado algunas

**Comment by pliskin12** [comment]
Ahh, solo te devuelve las que si inició, o sea que tiene por lo menos un exercise, puede devolver 1, 2, 3 o 4

**Comment by nelsonjerezv** [comment]
estamos listos con esto entonces :+1:

**Comment by pliskin12** [comment]
En todo caso tienes como saber cual es, te dice el id de la practice en el objeto

**Comment by pliskin12** [comment]
buena, cierra nomas las que estén listas
