### ISSUE TITLE
Solicitud API - Read tabla tests

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#36]
Holaa, les quiero solicitar lo siguiente:

son métodos para obtener las tablas(como un array pensaba) de
- tests con sus atributos

la idea es disponer de la info como se ve en estos json:
https://github.com/FeloVilches/Webforge-Express/tree/grupo1_nelson/public/jsonDataAux (ej questions y alternative)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Supongo que esto es en el contexto de un usuario no? Onda, ver los tests para el usuario en especifico. Si es así, ya está implementado. Dime si necesitas si o si TODOS los tests, de todos los usuarios de la plataforma. Felipe creó esos JSONS de esa forma con usuarios mezclados para poder trabajar mientras le haciamos la API, pero como te digo, ya está hecho para obtener todas las notas de UN usuario con : 
GET /api/v2/users/idUsuario/grades

**Comment by nelsonjerezv** [comment]
listo entonces, no necesito nada más :+1:
