### ISSUE TITLE
Solicitud API - read tabla evaluations

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#37]
Holaa, les quiero solicitar lo siguiente:

son métodos para obtener las tablas(como un array pensaba) de
- evaluation con atributos

la idea es disponer de la info como se ve en estos json:
https://github.com/FeloVilches/Webforge-Express/tree/grupo1_nelson/public/jsonDataAux (ej questions y alternative)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Ya está implementado... En GET /api/v2/evaluations
