### ISSUE TITLE
Solicitud API - Read tabla topics

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#38]
Holaa, les quiero solicitar lo siguiente:

son métodos para obtener las tablas(como un array pensaba) de
- topics con atributos

la idea es disponer de la info como se ve en estos json:
https://github.com/FeloVilches/Webforge-Express/tree/grupo1_nelson/public/jsonDataAux (ej questions y alternative)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by Angerback** [comment]
La tabla Topics no existe. Te referieres a Heuristics?

**Comment by nelsonjerezv** [comment]
no, me refiero a topics, según veo en el modelo de datos, y en las seeds, del proyecto, existe topics, que clasifica a questions

**Comment by pliskin12** [comment]
Si, despues me di cuenta Nelson. Pensé que no se usaba porque antes se sacaba de otro controlador.

https://github.com/Angerback/webforge/commit/692637df8ee8bb36be460ce4acd94869fafb9725

Está implementado en ese commit. GET /api/v2/topics

**Comment by nelsonjerezv** [comment]
Gracias :+1:
