### ISSUE TITLE
Solicitud API - Read tabla composition

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#41]
Holaa, les quiero solicitar lo siguiente:

son métodos para obtener las tablas(como un array pensaba) de
- composition con atributos

la idea es disponer de la info como se ve en estos json:
https://github.com/FeloVilches/Webforge-Express/tree/grupo1_nelson/public/jsonDataAux (ej questions y alternative)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by Angerback** [comment]
La tabla composition no existe.

**Comment by pliskin12** [comment]
Listo, revisa en la ruta api/v2/compositions y ve si es el json que necesitabas.

**Comment by pliskin12** [comment]
Por favor revisa lo implementado y cierra la petición si se satisface tu requerimiento.

**Comment by nelsonjerezv** [comment]
perfecto, gracias :+1:
