### ISSUE TITLE
Solicitud API - Create en tabla test

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#42]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para crear un nuevo test del estudiante(crear la evaluación cuando se presione "comenzar evaluación")

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by ChrisVilches** [comment]
Edita el titulo a todas las peticiones, ponles un titulo descriptivo y que sea fácil de identificar sin tener que leer todo. Gracias

**Comment by pliskin12** [comment]
Listo, en la ruta api/v2/users/idUsuario/tests con una petición POST se debe enviar un  JSON del tipo:
{"user_id": 2,"evaluation_id":1, "grade":4}
El id del usuario en el objeto es innecesario, ya que ya está en la url, pero puedes enviarlo sin problemas. 
La respuesta correcta es:

{
"outcome": "Test registrado exitosamente."
}

La respuesta si te falta la evaluación es:
{
"outcome": "Falta especificar evaluación."
}

En caso de error:
{
"outcome": "Error al registrar test"
}

**Comment by pliskin12** [comment]
Por favor revisa lo implementado y cierra la petición si se satisface tu requerimiento.

**Comment by nelsonjerezv** [comment]
me puedes confirmar que existe? no lo encuentro en esa ruta(staging)

**Comment by pliskin12** [comment]
Funcionando sin problemas.
![prueba2](https://cloud.githubusercontent.com/assets/11650986/16326292/ac88d2a4-399b-11e6-8791-7a8fdd5716f0.png)

**Comment by nelsonjerezv** [comment]
Error de typeo mío, gracias :+1:
