### ISSUE TITLE
Solicitud API - create en tabla answers

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#43]
Holaa, les quiero solicitar lo siguiente:
- necesito un método para guardar la respuesta de la pregunta actual en la evaluación actual(se guarda cada vez que presiona siguiente pregunta en la evaluación)

Gracias!!

favor señalen todas las dudas que se generen ;)

**Comment by PabloSalinasM** [comment]
leido, cambiar titulo

**Comment by pliskin12** [comment]
Listo, en la ruta api/v2/tests/idTest/answers con una petición POST se debe enviar un JSON del tipo:
{"question_id":1,"alternative":1}
El id del test en el objeto es innecesario, ya que ya está en la url, pero puedes enviarlo sin problemas.
La respuesta correcta es:

{
"outcome": "Respuesta registrada exitosamente."
}

La respuesta si te falta la pregunta es:
{
"outcome": "Falta especificar pregunta."
}

En caso de error:
{
"outcome": "Error al registrar respuesta."
}

**Comment by pliskin12** [comment]
Por favor revisa lo implementado y cierra la petición si se satisface tu requerimiento.

**Comment by nelsonjerezv** [comment]
me puedes confirmar que existe? no lo encuentro en esa ruta(staging)

**Comment by pliskin12** [comment]
Puedes hacerlo local o en el servidor staging:
![prueba1](https://cloud.githubusercontent.com/assets/11650986/16326110/6adff982-399a-11e6-8d29-6d145f0e4033.png)

**Comment by nelsonjerezv** [comment]
error mío, gracias :+1:
