### ISSUE TITLE
Peticion API - Read en tabla practices

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#46]
Hola, necesito poder leer las practicas por defecto que vienen en webforge.

Gracias :)

**Comment by nelsonjerezv** [comment]
no es necesario

**Comment by nelsonjerezv** [comment]
la avancé por mi cuenta, se las dejo por si les acelera el proceso

class Api::V2::PracticesController < API::V2::ApiController
    def index
        @practices = Practice.all
    end
end

(index.json.jbuilder)
json.array!(@practices) do |practice|
    json.extract! practice, :id, :name, :description, :plunk, :embed
end

(routes.rb)
#Practices
    get 'practices', to: 'practices#index'

**Comment by pliskin12** [comment]
Lo implementamos como sugeriste y funcionó bien
