### ISSUE TITLE
Errores en diccionario de datos

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#47]
pesquen esto solo si saben que alguien más lo está usando.

hay pequeños errores, como por ejemplo, en practices (que es en realidad Practice) el atributo es plunk, no plunker

**Comment by pliskin12** [comment]
Hablaré esto con mi scrum master

**Comment by PabloSalinasM** [comment]
ok javier redacto super bien entonces XD

**Comment by PabloSalinasM** [comment]
actualizado el diccionario es más conceptual se cambiaron las imagenes para que no exista ambiguedad.Saludos

https://docs.google.com/document/d/1dOBTEhngA5YH_EyZXWeQnTZ2uxzacv6dF-lWnxw2HrA/edit#
