### ISSUE TITLE
Petición API - Método para guardar Token y correo de login

### ISSUE THREAD

**Issue by yeremix** [Angerback/webforge#48]
necesito un método para guardar en memoria el token y el email del usuario logeado y ademas un método para destruir la sesión (libre formato json y url)

**Comment by pliskin12** [comment]
Leída

**Comment by pliskin12** [comment]
Listo, para iniciarl sesión usa la ruta api/v2/users/start_session con una petición POST y envía un objeto JSON del tipo: {"email": "alexis.casanueva@usach.cl","token":"tokencito"}
Si todo sale bien, te dirá:
{
          outcome: "Login exitoso."
       }

Si ya está logueado:
{
        outcome: "Ya está logueado."
     }
Si el usuario derechamente no existe (porque una cosa es que exista en google y otra que exista en webforge):
{
          outcome: "Usuario no existe."
       }

**Comment by pliskin12** [comment]
Para cerrar la sesión, usa la ruta api/v2/users/end_session con una petición POST y envía un objeto JSON del tipo: {"token":"tokencito"}

Si el usuario estaba logueado, te dirá:
{
        outcome: "Sesión cerrada."
     }

Si no:
{
        outcome: "Sesión no existe."
     }

**Comment by yeremix** [comment]
ok
