### ISSUE TITLE
Poblado BD webforge

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#49]
Una duda, lo presente en la app es únicamente lo que se encuentra en seeds.rb?

acá está seeds.rb :

https://github.com/Angerback/webforge/blob/staging/db/seeds.rb

**Comment by pliskin12** [comment]
Si, eso es todo lo que hay por defecto. Si hay algo más es solo porque se ha agregado durante las demo review o que los integrantes estén probando algo. En general, se resetea todo para la demo, por lo que si necesitan un nuevo fixture de datos para siemrpe deben solicitarlo por acá, pero deben proveernos los datos. Nuestra tarea es agregarlos en el lenguaje de Ruby.

**Comment by nelsonjerezv** [comment]
Gracias
