### ISSUE TITLE
Modificaron el schema.rb pero no las migraciones

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#5]
Este commit https://github.com/Angerback/webforge/commit/e0479df2fe85bcbcf06305489585afa2c86e36ca
Muestra que se modifico el archivo schema.rb, pero no las migraciones. Este cambio debe hacerse en las migraciones (no es buena practica modificar schema.rb manualmente)

**Comment by pliskin12** [comment]
Hola, gracias por comentarlo. Nuestro equipo se encuentra trabajando en ello.

**Comment by ghost** [comment]
deshice los cambios y agrege la migración respectiva a la rama Backend_con_frontend_experimental
