### ISSUE TITLE
Servicio para obtener las heuristicas

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#50]
Necesito servicios para mostrar las heuristicas, junto a todas las cosas necesarias para poder mostrarls (Do's, Don'ts, examples, etc)

El codigo deberia ser similar al del controlador original:
https://github.com/Angerback/webforge/blob/staging/app/controllers/heuristics_controller.rb

Y si es posible en el show, que cada heuristica venga con la ID y nombre de la siguiente y anterior. 

(De no ser asi, tendria que hacer dos consultas extra para cada heuristica, las cuales vendrian con mucha informacion que no necesito, por lo que seria algo ineficiente)

**Comment by pliskin12** [comment]
Leido

**Comment by pliskin12** [comment]
Entonces el index lo quieres general, y el show detallado con los dos, donts, heuristica anterior y siguiente?

**Comment by pliskin12** [comment]
Implementé lo que entendí a la primera, que es básicamente lo que ya estaba hecho por Javier. Si necesitas algo extra dime nomás, si no cierra la petición.

Para obtener todas las heuristicas usar GET /api/v2/heuristics
Para obtener una y todos los datos que solicitaste, GET /api/v2/heuristics/IdDeLaHeuristica

**Comment by ChrisVilches** [comment]
Sirvio perfectamente y pude hacer la HU requerida sin problemas, gracias :smirk:

La cerrare.
