### ISSUE TITLE
Solicitud API - Reemplazar código por proporcionado

### ISSUE THREAD

**Issue by nelsonjerezv** [Angerback/webforge#51]
Hola, dado que se suministran por medio de la API la información por separado de cada tabla referente al módulo de evaluaciones, en el archivo 

https://github.com/Angerback/webforge/blob/staging/app/views/api/v2/evaluations/index.json.jbuilder

solicito quitar ":questions", y reemplazarlo por ":image", cosa quede así:

json.extract! evaluation, :id, :name, :description, :image, :created_at, :updated_at

Gracias

**Comment by PabloSalinasM** [comment]
leida

**Comment by pliskin12** [comment]
Listo, probar

**Comment by nelsonjerezv** [comment]
perfecto, gracias :+1:
