### ISSUE TITLE
Bug en /api/v1/bank_accounts/{id}

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#58]
No se si sera un bug pero, esa URL no funciona en la rama webforge-staging.

En la version original de webforge, al entrar a `http://blooming-coast-9431.herokuapp.com/api/v1/bank_accounts/4?format=json`

Arroja este resultado:

``` json
{"id":7,"balance":1886,"user_id":4,"status":"Activa"}
```

En cambio con la rama que tengo yo (webforge-staging) me arroja un error de Ruby on Rails. Saben como arreglarlo? o es un bug que hay que arreglar?

**Comment by pliskin12** [comment]
leido

**Comment by ChrisVilches** [comment]
Companeros esta peticion es necesaria para gran parte de nuestras HU, por lo que solicito que se haga lo mas pronto posible, muchas gracias :smile:

**Comment by pliskin12** [comment]
Lo estoy viendo ahora mismo

**Comment by pliskin12** [comment]
Felipe, no es un bug. Lo que pasa es que no hay ninguna cuenta bancaria creada. Acabo de crear una con la url:
http://webforge-staging.herokuapp.com/api/v1/bank_accounts/   metodo POST
y el objeto: {"balance": 10, "status": "Activa", "user_id": 1}
eso crearía una cuenta bancaria para ismael vicencio.

Ahora, si entras a la url que me mencionas: 
http://webforge-staging.herokuapp.com/api/v1/bank_accounts/1?format=json
Funciona, ya que la cuenta existe. Supongo que Javier no creó un metodo para ver todas las cuentas por temas de seguridad. Si quieres, puedo poblar los seeds con cuentas por defecto, ya que cada vez que lo encesitamos hacemos un wipe de la base de datos con los valores por defecto. Dejame los datos y yo te los ingreso al seeds para que no los pierdan.

**Comment by pliskin12** [comment]
Ah lo otro, "?format=json" es innecesario ya que la api por defecto pasa todo con json
