### ISSUE TITLE
Calificaciones del curso de cierto alumno, para cierta evaluación.

### ISSUE THREAD

**Issue by Arapuntocom** [Angerback/webforge#59]
hola! para un determinado id de Usuario, e id de Evaluación, necesitamos un get que nos retorne el conjunto de calificaciones (solo las notas) que han obtenido los compañeros de Curso del usuario, en la evaluación.

**Comment by PabloSalinasM** [comment]
leído

**Comment by Arapuntocom** [comment]
:'(
qué tengo que hacer para ser atendida? (no creo que quiera que empiece a quitarme la ropa ps..)

**Comment by nelsonjerezv** [comment]
no puedo decidir si apoyarte o ponerme en tu contra xd

**Comment by PabloSalinasM** [comment]
Dependerá del seba xD

**Comment by pliskin12** [comment]
Ahora me pongo a trabajar en esta. Necesitas las calificaciones de los puros compañeros? No del usuario?

**Comment by pliskin12** [comment]
El tema es que ya hay cursos definidos en la plataforma. Necesitas los compañeros literalmente de curso, es decir, aquellos que están agregados a un mismo curso, o los que rindieron la misma evaluación, independiente del curso en el que estén?

**Comment by nelsonjerezv** [comment]
seba lo veo de dos formas válidas:
- 1) para todos los en curso == al estudiante que hace la petición, agarrar la ÚLTIMA nota mayor a 0.9(valor que usamos por defecto para una evaluación aún no calificada) para esa evaluación y devolver el promedio.
- 2) para todos los en curso == al estudiante que hace la petición, agarrar TODAS las notas mayores a 0.9(valor que usamos por defecto para una evaluación aún no calificada) para esa evaluación y devolver el promedio.

considera parámetros (idUser, idEvaluacion) o los que estimes convenientes.

**Comment by pliskin12** [comment]
Oka ahora me quedó más claro. Voy a ver si entendí con un ejemplo:
Tengo este curso:
Curso 1 : 
- Juanito: Evaluación 1: 3.4
- Jorgito: Evaluación 1: 4.4
- Jaimito: Evaluación 1: 5.0

Curso 2 : 
- Jorgito: Evaluación1: 4.4
- Andreita: Evaluación 1: 5.0

Si hiciera la petición para Juanito, con la evaluación 1, solo debería devolverme las notas de Jorgito y Jaimito, pero no la de Andreita, ya que no son compañeros de curso. ¿Es así?

**Comment by nelsonjerezv** [comment]
exacto, es restringido al curso del solicitante y a la evaluación solicitada. Adicionalmente, pensando en una peticion futura, para el caso 1 de los que te propuse, nos serviría tener dos numeros, cuantos en la última evaluación tienen nota menor a la última nota del solicitante y cuantos hay en el curso, onda tener una respuesta:

(promedioCurso, 
cantidadCompañerosDeCursoConUltimaNotaMenorASolicitante, 
CantidadEstudiantesEnCurso)

**Comment by pliskin12** [comment]
Listo. Probar en: api/v2/users/:user_id/evaluations/:evaluation_id/compare
