### ISSUE TITLE
No cargan Usuarios 

### ISSUE THREAD

**Issue by FVergaraP** [Angerback/webforge#62]
Al momento de ingresar a:

http://webforge-express.herokuapp.com/#!/users

y al seleccionar un usuario de un curso, por ejemplo:

http://webforge-express.herokuapp.com/#!/courses/1

No aparece

**Comment by ghost** [comment]
Y entrando a esta URL:

http://webforge-staging.herokuapp.com/api/v2/users

Entrega este mensaje 

``` json
{"status":"500","error":"Internal Server Error"}
```

Deberia mostrar la lista de usuarios

**Comment by pliskin12** [comment]
Solucionado, era un problema de heroku. Ahora funciona.
