### ISSUE TITLE
Agregar cuentas de banco a la poblacion inicial

### ISSUE THREAD

**Issue by ChrisVilches** [Angerback/webforge#63]
Para que funcione la terminal bancaria y se vea correctamente con sus funcionalidades, es necesario que haya una cuenta en la poblacion inicial de la aplicacion. 

Esto es por lo que dijo @Angerback en el otro issue:

```
[...] Lo que pasa es que no hay ninguna cuenta bancaria creada. Acabo de crear una con la url:
http://webforge-staging.herokuapp.com/api/v1/bank_accounts/ metodo POST
y el objeto: {"balance": 10, "status": "Activa", "user_id": 1}
eso crearía una cuenta bancaria para ismael vicencio.
```

**Comment by PabloSalinasM** [comment]
leído,

**Comment by pliskin12** [comment]
En proceso

**Comment by pliskin12** [comment]
https://github.com/Angerback/webforge/commit/b0ab6b2cea90f24abc575a6339d9702b5c81052e
