### ISSUE TITLE
Poblar evaluaciones

### ISSUE THREAD

**Issue by Arapuntocom** [Angerback/webforge#64]
Gente linda, lamento hacer peticiones tan tardíamente, pero no le habíamos tomado importancia a mostrar toooodas las evaluaciones de la plataforma. Hasta el momento, el enlace http://webforge-staging.herokuapp.com/api/v2/evaluations solo entrega 1 evaluación.  Sin embargo, para que el módulo sea operativo, entiendo que es necesario que además sean pobladas las tablas de evaluations, questions, compositions y tal vez alternatives. 

gracias.

**Comment by PabloSalinasM** [comment]
leída

**Comment by Arapuntocom** [comment]
Gente linda, ya no es necesario resolver la petición, ya que en la aplicación de Javier tampoco se muestra la 2da evaluación.
